# The latest LTS version of node
FROM node:alpine

# Create app directory
WORKDIR /usr/src/app

ENV NODE_ENV="production"
ENV BABEL_ENV="production"

# Add app
COPY . .

# Install app dependencies
RUN yarn install --silent

# Build app
RUN yarn build --silent

# Make port 4001 available to the world outside this container
EXPOSE 4001

# Start the app
CMD ["yarn", "prodServer"]

# Run Mosquitto
# docker run -it -p 1883:1883 -p 9001:9001 -v mosquitto.conf:/mosquitto/config/mosquitto.conf -v /mosquitto/data -v /mosquitto/log eclipse-mosquitto