## Build Environment
# The latest LTS version of node
FROM arm32v7/node:9.11.1-stretch as builder

# Create app directory
WORKDIR /usr/src/app

ENV NODE_ENV="production"
ENV BABEL_ENV="production"

# Add app
COPY . .

# Install app dependencies
RUN yarn install --silent

# Install pkg
RUN yarn global add pkg

# Build app
RUN yarn build

CMD ["yarn", "prodServer"]

## Prod Environment
FROM arm32v7/node:9.11.1-stretch
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/lightapp2-server /usr/src/app

# Make port 4001 available to the world outside this container
EXPOSE 4001

# Start the app
CMD ./lightapp2-server

# Run Mosquitto
# docker run -it -p 1883:1883 -p 9001:9001 -v mosquitto.conf:/mosquitto/config/mosquitto.conf -v /mosquitto/data -v /mosquitto/log eclipse-mosquitto